# Generated by Django 3.1.2 on 2021-08-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_description',
            field=models.CharField(default='title description', max_length=250),
        ),
    ]
