# Generated by Django 2.2.14 on 2021-08-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/user.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='images'),
        ),
    ]
