# Generated by Django 2.2.14 on 2021-08-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210824_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/images/user.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='images'),
        ),
    ]
