# Generated by Django 2.2.14 on 2021-08-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210825_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
