# Generated by Django 2.2.14 on 2021-09-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210915_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/images/avatar2.png', null=True, upload_to='images'),
        ),
    ]
